source "https://rubygems.org"

gem "jekyll", "3.9.3"
gem "html-proofer", "3.19.4"
gem "jekyll-remote-theme"
gem "deep_merge"
gem 'jekyll-open-sdg-plugins', git: 'https://github.com/open-sdg/jekyll-open-sdg-plugins.git', branch: '2.4.0-dev'
gem "kramdown-parser-gfm"
gem "webrick"
